import { describe, expect, it } from 'vitest'; import { AuthService } from '../src/auth/auth_service.js';
class Verifier { subject='apple-1'; async verify(_token:string,_nonce:string){return {sub:this.subject};} }
class Apple { fail=false; async exchange(_code:string){return {refreshToken:'apple-refresh'};} async revoke(_token:string){if(this.fail)throw new Error('REVOKE_FAILED');} }
const setup=()=>{const verifier=new Verifier();const apple=new Apple();const auth=new AuthService(verifier,apple,'test-jwt-secret-which-is-long-enough-32',Buffer.alloc(32,9));return {auth,verifier,apple};};
async function login(auth:AuthService,installationId='00000000-0000-4000-8000-000000000001',displayName='Ada',email='a@example.com'){const c=auth.challenge(installationId);return auth.login({challengeId:c.challengeId,identityToken:'signed',authorizationCode:'code',returnedState:c.state,installationId,platform:'ios',displayName,email});}
describe('AuthService',()=>{
 it('rejects used, expired, wrong state and wrong installation challenges',async()=>{const {auth}=setup();const c=auth.challenge('i');await expect(auth.login({challengeId:c.challengeId,identityToken:'x',authorizationCode:'x',returnedState:'wrong',installationId:'i',platform:'ios'})).rejects.toThrow('AUTH_CHALLENGE_INVALID');const d=auth.challenge('i');const stored=auth.challenges.get(d.challengeId)!;stored.expires=0;await expect(auth.login({challengeId:d.challengeId,identityToken:'x',authorizationCode:'x',returnedState:d.state,installationId:'i',platform:'ios'})).rejects.toThrow('AUTH_CHALLENGE_INVALID');const e=auth.challenge('i');await expect(auth.login({challengeId:e.challengeId,identityToken:'x',authorizationCode:'x',returnedState:e.state,installationId:'other',platform:'ios'})).rejects.toThrow('AUTH_CHALLENGE_INVALID');});
 it('uses Apple subject identity and preserves missing profile fields',async()=>{const {auth,verifier}=setup();const first=await login(auth);const second=await login(auth,'00000000-0000-0000-0000-000000000002','','');expect(second.user.id).toBe(first.user.id);expect(second.user.displayName).toBe('Ada');expect(second.user.email).toBe('a@example.com');verifier.subject='apple-2';const other=await login(auth,'00000000-0000-0000-0000-000000000003','Other','a@example.com');expect(other.user.id).not.toBe(first.user.id);});
 it('rotates refresh tokens and revokes logout sessions',async()=>{const {auth}=setup();const first=await login(auth);const next=await auth.refresh(first.session.refreshToken);expect(next.session.refreshToken).not.toBe(first.session.refreshToken);await expect(auth.refresh(first.session.refreshToken)).rejects.toThrow('REFRESH_INVALID');await auth.logout(`Bearer ${next.session.accessToken}`);await expect(auth.refresh(next.session.refreshToken)).rejects.toThrow('REFRESH_INVALID');});
 it('upserts devices and allows more than two devices',async()=>{const {auth}=setup();const first=await login(auth,'00000000-0000-0000-0000-000000000011');const again=await login(auth,'00000000-0000-0000-0000-000000000011');expect((await auth.devicesFor(`Bearer ${again.session.accessToken}`))).toHaveLength(1);await login(auth,'00000000-0000-0000-0000-000000000012');await login(auth,'00000000-0000-0000-0000-000000000013');expect((await auth.devicesFor(`Bearer ${first.session.accessToken}`))).toHaveLength(3);});
 it('deletes only after Apple revoke succeeds',async()=>{const {auth,apple}=setup();const first=await login(auth);await auth.delete(`Bearer ${first.session.accessToken}`);expect(auth.users.size).toBe(0);expect(auth.devices.size).toBe(0);expect(auth.credentials.size).toBe(0);await expect(auth.refresh(first.session.refreshToken)).rejects.toThrow();const other=await login(auth);apple.fail=true;await expect(auth.delete(`Bearer ${other.session.accessToken}`)).rejects.toThrow('REVOKE_FAILED');expect(auth.users.size).toBe(1);});
});
