// SQL-heavy repository implementations are intentionally kept close to the contracts.
// @ts-nocheck
// @ts-nocheck
import type { Pool, PoolClient } from 'pg';
import { pool } from './pool.js';
export type DbExecutor = Pick<Pool,'query'> | Pick<PoolClient,'query'>;
export type DbRow = Record<string,any>;
export interface AuthChallengeRepository { create(c:{id:string;nonceHash:string;state:string;installationId:string;expiresAt:Date}):Promise<void>; findById(db:DbExecutor,id:string):Promise<DbRow|null>; findByIdForUpdate(db:DbExecutor,id:string):Promise<DbRow|null>; markUsed(db:DbExecutor,id:string):Promise<void>; }
export interface UserRepository { findByAppleSubject(db:DbExecutor,s:string):Promise<DbRow|null>; findById(db:DbExecutor,id:string):Promise<DbRow|null>; create(db:DbExecutor,s:string,n:string|null,e:string|null):Promise<DbRow>; updateMissingProfile(db:DbExecutor,id:string,n:string|null,e:string|null):Promise<DbRow|null>; delete(db:DbExecutor,id:string):Promise<void>; }
export interface AppleCredentialRepository { findByUserId(db:DbExecutor,id:string):Promise<DbRow|null>; upsertEncryptedRefreshToken(db:DbExecutor,id:string,v:string):Promise<void>; deleteByUserId(db:DbExecutor,id:string):Promise<void>; }
export interface DeviceRepository { upsertByUserAndInstallation(db:DbExecutor,u:string,i:string,p:string,l:string,v?:string):Promise<DbRow>; listByUser(db:DbExecutor,id:string):Promise<DbRow[]>; findById(db:DbExecutor,id:string):Promise<DbRow|null>; updateLastSeen(db:DbExecutor,id:string):Promise<void>; deleteByUser(db:DbExecutor,id:string):Promise<void>; }
export interface SessionRepository { create(db:DbExecutor,v:{id:string;userId:string;deviceId:string;refreshHash:string;expiresAt:Date}):Promise<DbRow>; findActiveByRefreshHash(db:DbExecutor,h:string):Promise<DbRow|null>; findActiveByRefreshHashForUpdate(db:DbExecutor,h:string):Promise<DbRow|null>; rotateRefresh(db:DbExecutor,id:string,h:string,e:Date):Promise<void>; revokeById(db:DbExecutor,id:string):Promise<void>; revokeAllByUser(db:DbExecutor,id:string):Promise<void>; revokeAllByDevice(db:DbExecutor,id:string):Promise<void>; }
const one=async(db:DbExecutor,sql:string,args:any[]=[])=> (await db.query(sql,args)).rows[0]??null;
export class PgAuthChallengeRepository implements AuthChallengeRepository { create(c){if(!pool)throw new Error('DATABASE_NOT_CONFIGURED');return pool.query('INSERT INTO auth_challenges(id,nonce_hash,state,installation_id,expires_at) VALUES($1,$2,$3,$4,$5)',[c.id,c.nonceHash,c.state,c.installationId,c.expiresAt]).then(()=>undefined);} findById(db,id){return one(db,'SELECT * FROM auth_challenges WHERE id=$1',[id]);} findByIdForUpdate(db,id){return one(db,'SELECT * FROM auth_challenges WHERE id=$1 FOR UPDATE',[id]);} markUsed(db,id){return db.query('UPDATE auth_challenges SET used_at=now() WHERE id=$1',[id]).then(()=>undefined);} }
export class PgUserRepository implements UserRepository { findByAppleSubject(db,s){return one(db,'SELECT id,apple_subject,display_name,email FROM users WHERE apple_subject=$1',[s]);} findById(db,id){return one(db,'SELECT id,apple_subject,display_name,email FROM users WHERE id=$1',[id]);} create(db,s,n,e){return one(db,'INSERT INTO users(apple_subject,display_name,email) VALUES($1,$2,$3) RETURNING id,apple_subject,display_name,email',[s,n,e]) as Promise<DbRow>;} updateMissingProfile(db,id,n,e){return one(db,'UPDATE users SET display_name=COALESCE(display_name,$2),email=COALESCE(email,$3),updated_at=now() WHERE id=$1 RETURNING id,apple_subject,display_name,email',[id,n,e]);} delete(db,id){return db.query('DELETE FROM users WHERE id=$1',[id]).then(()=>undefined);} }
export class PgAppleCredentialRepository implements AppleCredentialRepository { findByUserId(db,id){return one(db,'SELECT user_id,refresh_token_encrypted FROM apple_auth_credentials WHERE user_id=$1',[id]);} upsertEncryptedRefreshToken(db,id,v){return db.query('INSERT INTO apple_auth_credentials(user_id,refresh_token_encrypted) VALUES($1,$2) ON CONFLICT(user_id) DO UPDATE SET refresh_token_encrypted=EXCLUDED.refresh_token_encrypted,updated_at=now()',[id,v]).then(()=>undefined);} deleteByUserId(db,id){return db.query('DELETE FROM apple_auth_credentials WHERE user_id=$1',[id]).then(()=>undefined);} }
export class PgDeviceRepository implements DeviceRepository { upsertByUserAndInstallation(db,u,i,p,l,v){return one(db,'INSERT INTO devices(user_id,installation_id,platform,device_label,app_version) VALUES($1,$2,$3,$4,$5) ON CONFLICT(user_id,installation_id) DO UPDATE SET platform=EXCLUDED.platform,app_version=COALESCE(EXCLUDED.app_version,devices.app_version),last_seen_at=now(),revoked_at=NULL RETURNING *',[u,i,p,l,v]) as Promise<DbRow>;} listByUser(db,id){return db.query('SELECT id,installation_id,platform,device_label,app_version,last_seen_at FROM devices WHERE user_id=$1 AND revoked_at IS NULL ORDER BY last_seen_at DESC',[id]).then(r=>r.rows);} findById(db,id){return one(db,'SELECT * FROM devices WHERE id=$1',[id]);} updateLastSeen(db,id){return db.query('UPDATE devices SET last_seen_at=now() WHERE id=$1',[id]).then(()=>undefined);} deleteByUser(db,id){return db.query('DELETE FROM devices WHERE user_id=$1',[id]).then(()=>undefined);} }
export class PgSessionRepository implements SessionRepository { create(db,v){return one(db,'INSERT INTO sessions(id,user_id,device_id,refresh_token_hash,expires_at) VALUES($1,$2,$3,$4,$5) RETURNING *',[v.id,v.userId,v.deviceId,v.refreshHash,v.expiresAt]) as Promise<DbRow>;} findActiveByRefreshHash(db,h){return one(db,'SELECT * FROM sessions WHERE refresh_token_hash=$1 AND revoked_at IS NULL AND expires_at>now()',[h]);} findActiveByRefreshHashForUpdate(db,h){return one(db,'SELECT * FROM sessions WHERE refresh_token_hash=$1 AND revoked_at IS NULL AND expires_at>now() FOR UPDATE',[h]);} rotateRefresh(db,id,h,e){return db.query('UPDATE sessions SET refresh_token_hash=$2,expires_at=$3,last_seen_at=now() WHERE id=$1 AND revoked_at IS NULL',[id,h,e]).then(()=>undefined);} revokeById(db,id){return db.query('UPDATE sessions SET revoked_at=now() WHERE id=$1',[id]).then(()=>undefined);} revokeAllByUser(db,id){return db.query('UPDATE sessions SET revoked_at=now() WHERE user_id=$1 AND revoked_at IS NULL',[id]).then(()=>undefined);} revokeAllByDevice(db,id){return db.query('UPDATE sessions SET revoked_at=now() WHERE device_id=$1 AND revoked_at IS NULL',[id]).then(()=>undefined);} }
export async function withTransaction<T>(work:(tx:PoolClient)=>Promise<T>):Promise<T>{if(!pool)throw new Error('DATABASE_NOT_CONFIGURED');const tx=await pool.connect();try{await tx.query('BEGIN');const v=await work(tx);await tx.query('COMMIT');return v;}catch(e){await tx.query('ROLLBACK');throw e;}finally{tx.release();}}
export const pgRepositories=()=>({challenges:new PgAuthChallengeRepository(),users:new PgUserRepository(),credentials:new PgAppleCredentialRepository(),devices:new PgDeviceRepository(),sessions:new PgSessionRepository()});
export const requireDb=()=>{if(!pool)throw new Error('DATABASE_NOT_CONFIGURED');return pool;};
