import { createHash, randomBytes, randomUUID } from 'node:crypto';
import { jwtVerify } from 'jose';
import type { AppleTokenVerifier } from './apple_token_verifier.js';
import type { AppleTokenExchange } from './apple_token_exchange.js';
import { accessToken, hashToken, newRefreshToken } from '../security/tokens.js';
import { decryptToken, encryptToken } from '../security/encryption.js';
import { withTransaction, requireDb, type DbRow, type AuthChallengeRepository, type UserRepository, type AppleCredentialRepository, type DeviceRepository, type SessionRepository } from '../db/repositories.js';
type Repos={challenges:AuthChallengeRepository;users:UserRepository;credentials:AppleCredentialRepository;devices:DeviceRepository;sessions:SessionRepository};
export class AuthService {
  constructor(private verifier:AppleTokenVerifier, private apple:AppleTokenExchange, private jwtSecret:string, private encryptionKey:Buffer, private repos:Repos) {}
  async challenge(installationId:string){const c={id:randomUUID(),nonce:randomBytes(32).toString('base64url'),state:randomBytes(32).toString('base64url')};await this.repos.challenges.create({id:c.id,nonceHash:createHash('sha256').update(c.nonce).digest('hex'),state:c.state,installationId,expiresAt:new Date(Date.now()+300000)});return {challengeId:c.id,nonce:c.nonce,state:c.state};}
  async login(i:{challengeId:string;identityToken:string;authorizationCode:string;returnedState:string;installationId:string;platform:string;displayName?:string|null;email?:string|null;appVersion?:string}){const basic=await this.repos.challenges.findById(requireDb(),i.challengeId);if(!basic||basic.used_at||new Date(basic.expires_at).getTime()<Date.now()||basic.installation_id!==i.installationId||basic.state!==i.returnedState)throw new Error('AUTH_CHALLENGE_INVALID');const claims=await this.verifier.verify(i.identityToken,basic.nonce_hash);const exchanged=await this.apple.exchange(i.authorizationCode);return withTransaction(async tx=>{const c=await this.repos.challenges.findByIdForUpdate(tx,i.challengeId);if(!c||c.used_at||new Date(c.expires_at).getTime()<Date.now()||c.installation_id!==i.installationId||c.state!==i.returnedState)throw new Error('AUTH_CHALLENGE_INVALID');let u=await this.repos.users.findByAppleSubject(tx,claims.sub);if(!u)u=await this.repos.users.create(tx,claims.sub,i.displayName??null,i.email??null);else u=await this.repos.users.updateMissingProfile(tx,u.id,i.displayName??null,i.email??null)??u;if(exchanged.refreshToken)await this.repos.credentials.upsertEncryptedRefreshToken(tx,u.id,encryptToken(exchanged.refreshToken,this.encryptionKey));const d=await this.repos.devices.upsertByUserAndInstallation(tx,u.id,i.installationId,i.platform,i.platform==='ios'?'此 iPhone':'此设备',i.appVersion);const raw=newRefreshToken();const s=await this.repos.sessions.create(tx,{id:randomUUID(),userId:u.id,deviceId:d.id,refreshHash:hashToken(raw),expiresAt:new Date(Date.now()+60*24*3600_000)});await this.repos.challenges.markUsed(tx,i.challengeId);return this.response(u,s,raw);});}
  private async response(u:DbRow,s:DbRow,raw:string){return {user:{id:u.id,displayName:u.display_name,email:u.email},session:{accessToken:await accessToken(u.id,s.id,s.device_id,this.jwtSecret),refreshToken:raw,accessTokenExpiresAt:new Date(Date.now()+900000).toISOString()}};}
  async refresh(raw:string){return withTransaction(async tx=>{const s=await this.repos.sessions.findActiveByRefreshHashForUpdate(tx,hashToken(raw));if(!s)throw new Error('REFRESH_INVALID');const u=await this.repos.users.findById(tx,s.user_id);if(!u)throw new Error('REFRESH_INVALID');const next=newRefreshToken();await this.repos.sessions.rotateRefresh(tx,s.id,hashToken(next),new Date(Date.now()+60*24*3600_000));await this.repos.devices.updateLastSeen(tx,s.device_id);return this.response(u,s,next);});}
  private async claims(header?:string){if(!header?.startsWith('Bearer '))throw new Error('UNAUTHORIZED');const {payload}=await jwtVerify(header.slice(7),Buffer.from(this.jwtSecret));if(typeof payload.sub!=='string'||typeof payload.session_id!=='string')throw new Error('UNAUTHORIZED');return payload;}
  async authenticate(header?:string){const p=await this.claims(header);const u=await this.repos.users.findById(requireDb(),p.sub as string);if(!u)throw new Error('ACCOUNT_NOT_FOUND');return u;}
  async logout(header?:string){const p=await this.claims(header);await withTransaction(tx=>this.repos.sessions.revokeById(tx,p.session_id as string));}
  async devicesFor(header?:string){const p=await this.claims(header);const u=await this.repos.users.findById(requireDb(),p.sub as string);if(!u)throw new Error('ACCOUNT_NOT_FOUND');return (await this.repos.devices.listByUser(requireDb(),u.id)).map(d=>({id:d.id,installationId:d.installation_id,platform:d.platform,deviceLabel:d.device_label,appVersion:d.app_version,lastSeenAt:new Date(d.last_seen_at).toISOString(),current:d.id===p.device_id}));}
  async delete(header?:string){const p=await this.claims(header);const u=await this.repos.users.findById(requireDb(),p.sub as string);if(!u)throw new Error('ACCOUNT_NOT_FOUND');const credential=await this.repos.credentials.findByUserId(requireDb(),u.id);if(!credential)throw new Error('APPLE_CREDENTIAL_MISSING');await this.apple.revoke(decryptToken(credential.refresh_token_encrypted,this.encryptionKey));await withTransaction(async tx=>{await this.repos.sessions.revokeAllByUser(tx,u.id);await this.repos.credentials.deleteByUserId(tx,u.id);await this.repos.users.delete(tx,u.id);});}
}
